name: angel_gopher
version: 0.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0
  async: ^2.0.0
  gopher:
    path: ../gopher
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
